theme: jekyll-theme-minimal
logo: /assets/img/logo.png
title: DD Labs Faciliteter og Udstyr
description: FÃ¥ overblik over udstyr og faciliteter i DD Lab og Audiodesign.
github:
  is_project_page: false
