theme: jekyll-theme-minimal
logo: /assets/img/logo.png
title: DD Labs Faciliteter og Udstyr
description: Her kan du f√• et overblik over det udstyr og de faciliteter DD Lab har at tilbyde. Noget med Aarhus Universitet.
github:
  is_project_page: false
